### ISSUE TITLE
operator id should only be 2-4 characters long

### ISSUE THREAD

**Issue by stephen-ritchie** [stephen-ritchie/StartupDay#12]
Double check this with mom, but I believe operator ID needs to be at minimum 2 characters and max of 4.

**Comment by mrnetdes** [comment]
The cashier column in the transactionTBL is 3 characters, but I don't know if Mom has a minimum length in mind.
And the transactionID column is 15 characters, so I guess that implies that your timestamp is 11 characters, one character for the dash and 3 characters for the cashier.

**Comment by mrnetdes** [comment]
Mom says it should always be 3 characters, so update validation.py to say:
`if (len(userInput) != 3):`
 `           print(Fore.RED + "ID must be 3 characters" + Style.RESET_ALL)`
`            continue`

**Comment by mrnetdes** [comment]
And Mom doesn't want blanks in the operator id

**Comment by mrnetdes** [comment]
So try this in validation.py
`        # Checking that operator is valid`
`        if (userInput.isalpha() == False):`
 `          print(Fore.RED + "ID must be alphabetic characters" + Style.RESET_ALL)`
`           continue`

 `       if (len(userInput) != 3):`
  `          print(Fore.RED + "ID must be 3 characters" + Style.RESET_ALL)`
 `           continue`
 `       else:`
 `           break`

**Comment by mrnetdes** [comment]
Closed
