### ISSUE TITLE
No check for overpayment amounts

### ISSUE THREAD

**Issue by mrnetdes** [stephen-ritchie/StartupDay#7]
When entering a payment amount I can enter a value that is greater than the current outstanding balance.

**Comment by stephen-ritchie** [comment]
Good catch, I forgot I needed to implement that. Marking as a 'feature' and not ' bug' because the code has not been implemented yet.

**Comment by mrnetdes** [comment]
Also, you might want to think about checking for pay_in_full in the validation function and go ahead and set the amount equal to the outstanding balance, assuming it is available in the validation function.  You could always pass it as an argument if it is not a global.

**Comment by mrnetdes** [comment]
Here is a suggested way to add the overpayment check to get_payment_info.
I added a max_amount parameter to the code

def get_payment_amount(prompt, max_amount):
    """
    Args:
        prompt (str): contains the prompt that will be displayed to the screen
        max_amount (float): the maximum allowed amount i.e current balance

And changed your <0 check to the following

       if (userInput < 0) or (userInput > max_amount):
            print(Fore.RED + "\tAMOUNT MUST BE BETWEEN 0 AND " + str(max_amount) + Style.RESET_ALL)
            continue
        else:
            break

Then change the calls to get_payment_info to pass the outstanding value

amount = get_payment_amount("\tamount: ",outstanding) # MAR

**Comment by mrnetdes** [comment]
Closed
