### ISSUE TITLE
Credit Card fee not included in extended payment display on console output

### ISSUE THREAD

**Issue by mrnetdes** [stephen-ritchie/StartupDay#8]
Console output
---------------------------------------------------------------------------
PaymentType     Payment         Fee             extended_payment info           
---------------------------------------------------------------------------
credit          110.0           3.3             110.0           1234           

Do the above charges look correct?: y

I would expect the extended_payment to show 113.30.

**Comment by stephen-ritchie** [comment]
Also a good catch. I'll look into that. I think this is another case of me knowing it was wrong but forgetting to implement code to do the addition.

**Comment by mrnetdes** [comment]
Testing shows this is fixed.
